site_name: Peripety
theme: readthedocs

pages:
    - Introduction: 'index.md'
    
    - Audit Steps:
    
        - Racks: 'audit-steps/racks.md'
           - Rack Groups: 'audit-steps/sitegroup.md'
        - Devices: 'audit-steps/devices.md'
        - Manufacturer Library: 'audit-steps/manufacturers.md'
        - Device Type Library: 'audit-steps/device-types.md'
        - Cables: 'audit-steps/cables.md'
        
    - Cable and Connector Information:   
        - Cable Identification: 'audit-steps/cable_definitions.md'
        - Cable Pinouts: 'audit-steps/pinouts.md'
    
    - Connector Identification:
        - Connectors: 'audit-steps/connectors.md'
        - Power: 'audit-steps/power.md'
        
    - Field Definitions:
    
      - Site: 'field-definitions/site.md'
      - Rack: 'field-definitions/rack.md'
      - Device: 'field-definitions/device.md'

markdown_extensions:
    - admonition:
